using System.Collections.Generic;
using System.Linq;
using UnityEngine;

// Decorative match and spectators; deliberately independent from structural loads.
public sealed class VisualFootballCrowd : MonoBehaviour
{
    private readonly List<Object> resources=new List<Object>();
    private readonly List<Transform> players=new List<Transform>();
    private readonly List<Vector3> bases=new List<Vector3>();
    private readonly List<Transform> fans=new List<Transform>();
    private readonly List<Vector3> fanBases=new List<Vector3>();
    private readonly List<Transform> flags=new List<Transform>();
    private Transform ball;
    private float cx,cy,cz;
    private Material blue,orange,white,dark,skin,concrete;
    private Material Mat(string name,Color color)
    {var m=new Material(Shader.Find("Standard") ?? Shader.Find("Universal Render Pipeline/Lit")){name=name,color=color};resources.Add(m);return m;}
    private GameObject Piece(Transform parent,string name,Vector3 position,Vector3 size,Material mat,PrimitiveType type=PrimitiveType.Cube)
    {
        var obj=GameObject.CreatePrimitive(type);obj.name=name;obj.layer=2;obj.transform.SetParent(parent,false);
        obj.transform.localPosition=position;obj.transform.localScale=size;obj.GetComponent<Renderer>().sharedMaterial=mat;
        var collider=obj.GetComponent<Collider>();collider.enabled=false;if(Application.isPlaying)Destroy(collider);else DestroyImmediate(collider);return obj;
    }
    private Transform Person(string name,Vector3 p,Material shirt,bool cheer,float heading)
    {
        var root=new GameObject(name);root.layer=2;root.transform.SetParent(transform,false);root.transform.localPosition=p;
        Piece(root.transform,"Cabeza",new Vector3(0,1.57f,0),Vector3.one*.25f,skin,PrimitiveType.Sphere);
        Piece(root.transform,"Camiseta",new Vector3(0,1.08f,0),new Vector3(.43f,.65f,.24f),shirt);
        foreach(float side in new[]{-1f,1f})
        {
            Piece(root.transform,"Pierna",new Vector3(side*.12f,.39f,0),new Vector3(.14f,.72f,.16f),dark);
            Piece(root.transform,"Zapato",new Vector3(side*.12f,.055f,.065f),new Vector3(.18f,.11f,.29f),dark);
            var arm=Piece(root.transform,"Brazo",new Vector3(side*.32f,cheer?1.43f:1.08f,0),new Vector3(.12f,.60f,.14f),shirt);
            arm.transform.localRotation=Quaternion.Euler(0,0,side*(cheer?-32:12));
        }
        // Batch each person by material: three renderers instead of eight parts.
        var parts=root.GetComponentsInChildren<MeshRenderer>().ToArray();
        foreach(var group in parts.GroupBy(r=>r.sharedMaterial))
        {
            var mesh=new Mesh{name=name+"_"+group.Key.name};
            mesh.CombineMeshes(group.Select(r=>new CombineInstance{mesh=r.GetComponent<MeshFilter>().sharedMesh,
                transform=root.transform.worldToLocalMatrix*r.transform.localToWorldMatrix}).ToArray());resources.Add(mesh);
            var batch=new GameObject("Cuerpo_agrupado");batch.layer=2;batch.transform.SetParent(root.transform,false);
            batch.AddComponent<MeshFilter>().sharedMesh=mesh;batch.AddComponent<MeshRenderer>().sharedMaterial=group.Key;
        }
        foreach(var r in parts){r.enabled=false;if(Application.isPlaying)Destroy(r.gameObject);else DestroyImmediate(r.gameObject);}
        root.transform.localRotation=Quaternion.Euler(0,heading,0);return root.transform;
    }
    public void Build(float x,float y,float z,float width,float length)
    {
        cx=x;cy=y;cz=z;
        blue=Mat("Equipo_azul",new Color(.08f,.28f,.72f));orange=Mat("Equipo_naranja",new Color(.95f,.35f,.08f));
        white=Mat("Blanco_barra",new Color(.93f,.93f,.89f));dark=Mat("Pantalon_y_asientos",new Color(.12f,.15f,.19f));
        skin=Mat("Piel_personas",new Color(.66f,.44f,.28f));concrete=Mat("Graderia_hormigon",new Color(.57f,.57f,.53f));
        for(int team=0;team<2;team++)for(int n=0;n<11;n++)
        {
            float side=team==0?-1:1;
            float px=n==0?x:x+((n-1)%4-1.5f)*12;
            float pz=n==0?z+side*(length/2-2):z+side*(8+(n-1)/4*12);
            var p=new Vector3(px,y,pz);players.Add(Person("Jugador_equipo_"+team+"_"+(n+1),p,team==0?blue:orange,false,team==0?0:180));bases.Add(p);
        }
        var referee=new Vector3(x+7,y,z);players.Add(Person("Arbitro",referee,white,false,0));bases.Add(referee);
        ball=Piece(transform,"Balon",new Vector3(x,y+.12f,z),Vector3.one*.22f,white,PrimitiveType.Sphere).transform;
        float startX=x+width/2+4;
        // Tiers follow the 40% hillside profile generated by VisualCampusSite.
        for(int row=0;row<6;row++)
        {
            float rowX=startX+row*1.1f,level=y+.34f+row*.44f;
            Piece(transform,"Grada_talud_"+(row+1),new Vector3(rowX,level-.12f,z),new Vector3(1.1f,.24f,44),concrete);
            Piece(transform,"Banco_grada",new Vector3(rowX,level+.35f,z),new Vector3(.48f,.14f,44),dark);
            for(int seat=0;seat<9;seat++)
            {
                if((row+seat)%5==0)continue;
                var p=new Vector3(rowX+.38f,level,z-19+seat*4.6f);
                fans.Add(Person("Hincha_"+row+"_"+seat,p,(row+seat)%2==0?blue:orange,true,-90));fanBases.Add(p);
            }
        }
        Banner(new Vector3(startX-.55f,y+1.25f,z-12),"VAMOS INGENIERÍA",blue);
        Banner(new Vector3(startX-.55f,y+1.25f,z+11),"DALE EQUIPO",orange);
        for(int f=0;f<6;f++)
        {
            var p=new Vector3(startX+4,y+1.94f,z-20+f*8);
            Piece(transform,"Mastil_bandera",p+Vector3.up*1.5f,new Vector3(.06f,3,.06f),dark);
            var flag=Piece(transform,"Bandera_barra",p+new Vector3(0,2.5f,.8f),new Vector3(.045f,1.1f,1.6f),f%2==0?blue:orange);
            flags.Add(flag.transform);
        }
    }
    private void Banner(Vector3 p,string caption,Material mat)
    {
        Piece(transform,"Lienzo_barra",p,new Vector3(.08f,1.15f,9),mat);
        var obj=new GameObject("Texto_lienzo");obj.layer=2;obj.transform.SetParent(transform,false);obj.transform.localPosition=p+Vector3.left*.05f;
        obj.transform.localRotation=Quaternion.Euler(0,90,0);var text=obj.AddComponent<TextMesh>();text.text=caption;
        text.anchor=TextAnchor.MiddleCenter;text.fontSize=42;text.characterSize=.11f;text.color=Color.white;
    }
    private void Update()
    {
        if(!Application.isPlaying)return;
        float t=Time.time;
        for(int i=0;i<players.Count;i++)
        {
            float travel=i==0 || i==11? .4f:2;
            players[i].localPosition=bases[i]+new Vector3(Mathf.Sin(t*.45f+i)*travel,Mathf.Abs(Mathf.Sin(t*5+i))*.035f,Mathf.Sin(t*.31f+i*.7f)*travel);
        }
        if(ball!=null)ball.localPosition=new Vector3(cx+Mathf.Sin(t*.35f)*12,cy+.12f,cz+Mathf.Sin(t*.22f)*15);
        for(int i=0;i<fans.Count;i++)fans[i].localPosition=fanBases[i]+Vector3.up*(.025f*(1+Mathf.Sin(t*2.8f+i)));
        for(int i=0;i<flags.Count;i++)flags[i].localRotation=Quaternion.Euler(0,Mathf.Sin(t*2+i)*12,Mathf.Sin(t*1.5f+i)*5);
    }
    private void OnDestroy(){foreach(var item in resources)if(item!=null){if(Application.isPlaying)Destroy(item);else DestroyImmediate(item);}}
}
