using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using UnityEngine;
using Process = System.Diagnostics.Process;

[Serializable] public class SeismicPythonRuntime { public string executable; }
public sealed class SeismicPickTarget : MonoBehaviour { public int memberIndex; }

// Independent phase 1: data is generated by OpenSees; Unity only plays it.
public sealed class SeismicPlaybackController : MonoBehaviour
{
    public static SeismicPlaybackController Instance { get; private set; }
    public static bool IsActive => Application.isPlaying && Instance != null && Instance.response != null && Instance.panelVisible;
    private readonly float[] factors = { .25f, .5f, 1f, 1.5f };
    private readonly string[] factorNames = { "0.25x", "0.50x", "1.00x", "1.50x" };
    private readonly string[] directionNames = { "X", "Y" };
    private SeismicRecordCatalog catalog;
    private SeismicResponseData response;
    private int recordIndex, factorIndex = 2, directionIndex, selected = -1;
    private bool panelVisible, playing, showOriginal = true, isolateSelected;
    private float playTime, speed = 1f, visualScale = 50f;
    private string status = "Seleccione registro e intensidad; luego ejecute o cargue OpenSees.";
    private Process analysis;
    private readonly ConcurrentQueue<string> messages = new ConcurrentQueue<string>();
    private GameObject visualRoot, referenceRoot;
    private Material beamMaterial, columnMaterial, wallMaterial, ghostMaterial, selectedMaterial;
    private readonly List<MeshBar> bars = new List<MeshBar>();
    private readonly Dictionary<Renderer,bool> hiddenRenderers = new Dictionary<Renderer,bool>();
    private readonly Dictionary<Collider,bool> hiddenColliders = new Dictionary<Collider,bool>();
    private readonly Dictionary<Behaviour,bool> suspended = new Dictionary<Behaviour,bool>();
    private Vector3[] positions;
    private GUIStyle titleStyle, labelStyle, boxStyle, damageTitleStyle;
    private Texture2D panelTexture;
    private readonly SeismicCrackVisual crackVisual = new SeismicCrackVisual();
    private SeismicDamageHistory damageHistory;
    private int damageMember = -1;
    private bool showCracks = true;
    private Material crackedConcreteMaterial;
    private string damageError;
    private string memberQuery = "E1_229";
    private bool focusRequested;
    private readonly struct MeshBar
    {
        public readonly Transform transform;
        public readonly Renderer renderer;
        public readonly int nodeI, nodeJ, member;
        public readonly float width, height;
        public MeshBar(Transform t, Renderer r, int i, int j, int e, float w, float h)
        { transform=t; renderer=r; nodeI=i; nodeJ=j; member=e; width=w; height=h; }
    }
    private string SeismicPath => Path.GetFullPath(Path.Combine(Application.dataPath,"..","..","seismic"));
    private string ModelPath => DesktopModelFile.ActivePath;
    private string CurrentId => catalog.records[recordIndex].id+"_"+directionNames[directionIndex]+"_i"+
        Mathf.RoundToInt(factors[factorIndex]*100).ToString("000");
    public Rect PanelRect
    {
        get
        {
            StructureViewer viewer=GetComponent<StructureViewer>();
            float left=viewer != null && viewer.IsLeftPanelVisible() ? viewer.GetLeftPanelRect().xMax+16f : 16f;
            float height = selected >= 0 && response != null ? Mathf.Min(430f,Screen.height*.62f) : Mathf.Min(318f,Screen.height*.49f);
            return new Rect(left,Screen.height-height-15f,Mathf.Max(300f,Screen.width-left-15f),height);
        }
    }
    public static bool BlocksPointer(Vector2 mouse) => Instance != null && Instance.panelVisible && Instance.PanelRect.Contains(mouse);

    private void Awake() { Instance=this; }
    private void OnEnable() { Instance=this; }
    public void TogglePanel()
    {
        if (panelVisible) { Close(); return; }
        panelVisible=true;
        MobileLoadController.Instance?.SetPanelVisible(false);
        try
        {
            catalog=JsonUtility.FromJson<SeismicRecordCatalog>(File.ReadAllText(Path.Combine(SeismicPath,"records","catalog.json")));
            if (catalog?.records == null || catalog.records.Length == 0) throw new InvalidDataException("Catálogo vacío.");
        }
        catch (Exception e) { status=e.Message; catalog=null; }
    }

    private void Update()
    {
        if (!Application.isPlaying) return;
        while (messages.TryDequeue(out string line)) status=line;
        if (analysis != null && analysis.HasExited)
        {
            analysis.WaitForExit(); // Flush async output before installing the new state.
            while (messages.TryDequeue(out string lastLine)) status=lastLine;
            int code=analysis.ExitCode;
            analysis.Dispose(); analysis=null;
            if (code == 0 && panelVisible) LoadCurrent();
            else if (code == 0) status="Análisis completo; puede abrir el panel y cargarlo.";
            else status="ANÁLISIS RECHAZADO: " + status;
        }
        if (!IsActive) return;
        if (playing)
        {
            playTime=Mathf.Min(response.Metadata.duration,playTime+Time.unscaledDeltaTime*speed);
            if (playTime >= response.Metadata.duration) { playing=false; status="REGISTRO COMPLETO — respuesta elástica; chequeos nominales e ilustración de fisuras."; }
        }
        if (Input.GetMouseButtonDown(0) && !BlocksPointer(new Vector2(Input.mousePosition.x,Screen.height-Input.mousePosition.y)))
        {
            ElementPicker picker=GetComponent<ElementPicker>();
            if (picker == null || !picker.IsMouseOverViewerGui())
                if (Camera.main != null && Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition),out RaycastHit hit,1000f))
                {
                    SeismicPickTarget target=hit.collider.GetComponent<SeismicPickTarget>();
                    if (target != null) {selected=target.memberIndex;memberQuery=response.Metadata.members[selected].elementTag;}
                }
        }
        EnsureDamageHistory();
    }

    private void LateUpdate()
    {
        if (!IsActive) return;
        // The same interpolated node position is used by every connected member.
        int a=response.FrameAt(playTime), b=Mathf.Min(a+1,response.Metadata.frameCount-1);
        float blend=b == a ? 0 : Mathf.Clamp01((playTime-response.Time(a))/(response.Time(b)-response.Time(a)));
        for (int n=0;n<positions.Length;n++)
            positions[n]=response.OriginalNode(n)+Vector3.Lerp(response.ReadNode(a,n),response.ReadNode(b,n),blend)*visualScale;
        foreach (MeshBar bar in bars)
        {
            bar.renderer.enabled=!isolateSelected || selected<0 || bar.member==selected;
            PositionBar(bar.transform,positions[bar.nodeI],positions[bar.nodeJ],bar.width,bar.height);
            string type=response.Metadata.members[bar.member].type;
            Material material=bar.member == selected ? selectedMaterial :
                type == "muro_eq" ? wallMaterial : type == "columna" ? columnMaterial : beamMaterial;
            if (bar.member == selected && showCracks && damageHistory != null && damageMember==selected)
                material=crackedConcreteMaterial;
            if (bar.renderer.sharedMaterial != material) bar.renderer.sharedMaterial=material;
            if (bar.member == selected && damageMember==selected)
                crackVisual.Update(bar.transform,damageHistory,a,bar.width,bar.height,showCracks);
        }
        referenceRoot.SetActive(showOriginal && !isolateSelected);
        if(focusRequested) {focusRequested=false;FocusMemberNow();}
    }

    private void LoadCurrent()
    {
        if (catalog == null) return;
        if (StructuralModelEditor.ResultsStale) { status="Hay cambios de sección pendientes: ejecute primero el análisis del editor del modelo."; return; }
        string path=Path.Combine(DesktopModelFile.ResultsDirectory(SeismicPath),CurrentId+".json");
        if (!File.Exists(path)) { status="No hay respuesta calculada para esta intensidad/dirección. Pulse EJECUTAR OPENSEES."; return; }
        try
        {
            SeismicResponseData loaded=SeismicResponseData.Load(path,UnityData.Structure,
                SeismicResponseData.Hash(File.ReadAllBytes(ModelPath)));
            Restore(); response=loaded; playing=false; playTime=0; selected=-1;
            SuspendStaticView(); BuildVisuals();
            status="LISTO — análisis lineal Transient; valores reales. Seleccione una barra para leer sus extremos.";
        }
        catch (Exception e) { Restore(); status="No se cargó la respuesta: "+e.Message; Debug.LogWarning("[Seismic] "+e.Message); }
    }

    private void StartAnalysis()
    {
        if (analysis != null || catalog == null) return;
        if (StructuralModelEditor.ResultsStale) { status="Primero actualice el modelo con sus cambios de sección."; return; }
#if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
        Restore();
        try
        {
            string runtimePath=Path.Combine(SeismicPath,"runtime.local.json");
            string executable=File.Exists(runtimePath) ? JsonUtility.FromJson<SeismicPythonRuntime>(File.ReadAllText(runtimePath)).executable : "python";
            var info=new System.Diagnostics.ProcessStartInfo {
                FileName=executable,
                Arguments="-B \""+Path.Combine(SeismicPath,"transient_analysis.py")+"\" --record \""+
                    catalog.records[recordIndex].id+"\" --intensity "+factors[factorIndex].ToString(CultureInfo.InvariantCulture)+
                    " --direction "+directionNames[directionIndex]+" --model \""+ModelPath+"\" --output \""+DesktopModelFile.ResultsDirectory(SeismicPath)+"\"",
                WorkingDirectory=Path.GetFullPath(Path.Combine(SeismicPath,"..","..")),
                UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true
            };
            analysis=new Process { StartInfo=info };
            analysis.OutputDataReceived += (s,e) => { if (!string.IsNullOrEmpty(e.Data)) messages.Enqueue(e.Data); };
            analysis.ErrorDataReceived += (s,e) => { if (!string.IsNullOrEmpty(e.Data)) messages.Enqueue(e.Data); };
            analysis.Start(); analysis.BeginOutputReadLine(); analysis.BeginErrorReadLine();
            status="OPENSEES — calculando masas, modos, gravedad y respuesta Transient…";
        }
        catch (Exception e) { analysis?.Dispose(); analysis=null; status="No se pudo iniciar OpenSees: "+e.Message; }
#else
        status="El análisis se ejecuta en Windows/Editor. El teléfono requiere respuestas precalculadas.";
#endif
    }

    private void SuspendStaticView()
    {
        GetComponent<StructureViewer>()?.SuspendStaticDiagramsForSeismic();
        foreach (Behaviour component in GetComponents<Behaviour>())
            if (component is ElementPicker || component is ElementResultsPanel || component is SelectedBeamDiagramPanel ||
                component is PMPanel || component is DiagramController || component is MobileLoadController || component is MobileLoadLivePanel)
            { suspended[component]=component.enabled; component.enabled=false; }
        foreach (Renderer renderer in GetComponentsInChildren<Renderer>(true))
        { hiddenRenderers[renderer]=renderer.enabled; renderer.enabled=false; }
        foreach (Collider collider in GetComponentsInChildren<Collider>(true))
        { hiddenColliders[collider]=collider.enabled; collider.enabled=false; }
    }

    private static Material Material(Color color)
    {
        Shader shader=Shader.Find("Standard") ?? Shader.Find("Sprites/Default");
        Material material=new Material(shader); material.color=color;
        if (color.a < 1f && material.HasProperty("_Mode"))
        {
            material.SetFloat("_Mode",3);
            material.SetInt("_SrcBlend",(int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            material.SetInt("_DstBlend",(int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            material.SetInt("_ZWrite",0);
            material.EnableKeyword("_ALPHABLEND_ON"); material.renderQueue=3000;
        }
        return material;
    }
    private void BuildVisuals()
    {
        visualRoot=new GameObject("Seismic_OpenSees_deformed"); visualRoot.transform.SetParent(transform,false);
        referenceRoot=new GameObject("Seismic_original_reference"); referenceRoot.transform.SetParent(transform,false);
        beamMaterial=Material(new Color(.1f,.75f,.95f,1)); columnMaterial=Material(new Color(.25f,.3f,.4f,1));
        selectedMaterial=Material(Color.yellow);
        crackedConcreteMaterial=Material(new Color(.7f,.72f,.74f,1));
        wallMaterial=Material(new Color(.4f,.6f,.75f,1)); ghostMaterial=Material(new Color(.8f,.85f,.9f,.12f));
        positions=new Vector3[response.Metadata.nodeTags.Length];
        for (int e=0;e<response.Metadata.members.Length;e++)
        {
            SeismicMember member=response.Metadata.members[e];
            if (member.type == "brazo_rigido") continue; // Constraints have no visible physical section.
            int i=response.NodeIndex[member.nodeI],j=response.NodeIndex[member.nodeJ];
            foreach (bool ghost in new[] { false,true })
            {
                GameObject cube=GameObject.CreatePrimitive(PrimitiveType.Cube);
                cube.name=(ghost ? "Original_" : "Dynamic_")+member.elementTag;
                cube.transform.SetParent(ghost ? referenceRoot.transform : visualRoot.transform,false);
                PositionBar(cube.transform,response.OriginalNode(i),response.OriginalNode(j),member.width_m,member.height_m);
                Renderer renderer=cube.GetComponent<Renderer>();
                renderer.sharedMaterial=ghost ? ghostMaterial : member.type == "muro_eq" ? wallMaterial :
                    member.type == "columna" ? columnMaterial : beamMaterial;
                if (ghost) Destroy(cube.GetComponent<Collider>());
                else { cube.AddComponent<SeismicPickTarget>().memberIndex=e;
                    bars.Add(new MeshBar(cube.transform,renderer,i,j,e,member.width_m,member.height_m)); }
            }
        }
    }
    private static void PositionBar(Transform bar,Vector3 i,Vector3 j,float width,float height)
    {
        Vector3 axis=j-i;
        Vector3 reference=Mathf.Abs(axis.normalized.y)>.9f ? Vector3.right : Vector3.up;
        Vector3 side=Vector3.Cross(reference,axis).normalized;
        Vector3 localZ=Vector3.Cross(axis.normalized,side).normalized;
        bar.position=(i+j)*.5f;
        bar.rotation=Quaternion.LookRotation(localZ,axis.normalized);
        bar.localScale=new Vector3(width,axis.magnitude,height);
    }

    public void Close() { panelVisible=false; Restore(); }
    private void Restore()
    {
        playing=false; response=null;
        crackVisual.Clear(); damageHistory=null; damageMember=-1; damageError=null; selected=-1;focusRequested=false;
        DisposeRuntimeObject(visualRoot);
        DisposeRuntimeObject(referenceRoot);
        visualRoot=referenceRoot=null; bars.Clear(); positions=null;
        foreach (var pair in hiddenRenderers) if (pair.Key != null) pair.Key.enabled=pair.Value;
        foreach (var pair in hiddenColliders) if (pair.Key != null) pair.Key.enabled=pair.Value;
        foreach (var pair in suspended) if (pair.Key != null) pair.Key.enabled=pair.Value;
        hiddenRenderers.Clear(); hiddenColliders.Clear(); suspended.Clear();
        foreach (Material material in new[] {beamMaterial,columnMaterial,wallMaterial,ghostMaterial,selectedMaterial,crackedConcreteMaterial})
            DisposeRuntimeObject(material);
        beamMaterial=columnMaterial=wallMaterial=ghostMaterial=selectedMaterial=crackedConcreteMaterial=null;
    }
    private void OnDestroy()
    {
        Restore();
        if (Instance == this) Instance=null;
        StopAnalysis();
        DisposeRuntimeObject(panelTexture);
    }
    private void OnDisable()
    {
        panelVisible=false;Restore();StopAnalysis();
    }
    private void StopAnalysis()
    {
        if (analysis != null)
        {
            try { if (!analysis.HasExited) analysis.Kill(); }
            catch (InvalidOperationException) { }
            catch (System.ComponentModel.Win32Exception) { }
            analysis.Dispose();
            analysis=null;
        }
    }
    private static void DisposeRuntimeObject(UnityEngine.Object obj)
    {
        if(obj == null) return;
        if(Application.isPlaying) Destroy(obj); else DestroyImmediate(obj);
    }

    private void OnGUI()
    {
        if (!Application.isPlaying || !panelVisible) return;
        if (titleStyle == null)
        {
            titleStyle=new GUIStyle(GUI.skin.label) { fontSize=14,fontStyle=FontStyle.Bold };
            titleStyle.normal.textColor=new Color(.25f,.85f,1f);
            damageTitleStyle=new GUIStyle(titleStyle);damageTitleStyle.normal.textColor=Color.white;
            labelStyle=new GUIStyle(GUI.skin.label) { fontSize=14,wordWrap=true };
            panelTexture=new Texture2D(1,1); panelTexture.SetPixel(0,0,new Color(.035f,.055f,.08f,.97f)); panelTexture.Apply();
            boxStyle=new GUIStyle(GUI.skin.box); boxStyle.normal.background=panelTexture;
        }
        Rect rect=PanelRect;
        GUI.Box(rect,GUIContent.none,boxStyle);
        float x=rect.x+12,y=rect.y+8,w=rect.width-24;
        GUI.Label(new Rect(x,y,w-95,22),"SIMULACIÓN SÍSMICA — OPENSEES TRANSIENT",titleStyle);
        if (GUI.Button(new Rect(rect.xMax-85,y,70,22),"CERRAR")) Close();
        y+=26;
        bool previousEnabled=GUI.enabled;
        GUI.enabled=analysis == null && catalog != null;
        if (catalog != null)
        {
            string[] names=Array.ConvertAll(catalog.records,r=>r.name);
            int record=GUI.SelectionGrid(new Rect(x,y,Mathf.Max(180,w*.37f),25),recordIndex,names,names.Length);
            int factor=GUI.SelectionGrid(new Rect(x+w*.39f,y,w*.37f,25),factorIndex,factorNames,4);
            int direction=GUI.SelectionGrid(new Rect(x+w*.78f,y,w*.22f,25),directionIndex,directionNames,2);
            if (record != recordIndex || factor != factorIndex || direction != directionIndex)
            { Restore(); recordIndex=record; factorIndex=factor; directionIndex=direction; LoadCurrent(); }
        }
        y+=30;
        if (GUI.Button(new Rect(x,y,185,24),"EJECUTAR OPENSEES")) StartAnalysis();
        if (GUI.Button(new Rect(x+193,y,150,24),"CARGAR CALCULADO")) LoadCurrent();
        float statusOffset = 355f;
        if (response != null)
        {
            memberQuery=GUI.TextField(new Rect(x+355,y,160,24),memberQuery);
            if(GUI.Button(new Rect(x+521,y,128,24),"SELECCIONAR ID"))
            {
                int id;bool numeric=int.TryParse(memberQuery.Trim(),out id);
                int index=Array.FindIndex(response.Metadata.members,e=>
                    e.type!="brazo_rigido" && ((numeric && e.id==id) || string.Equals(e.elementTag,memberQuery.Trim(),StringComparison.OrdinalIgnoreCase)));
                if(index>=0) {selected=index;memberQuery=response.Metadata.members[index].elementTag;EnsureDamageHistory();}
                else status="ID/elementTag no encontrado en el análisis.";
            }
            statusOffset=661f;
        }
        GUI.enabled=previousEnabled;
        GUI.Label(new Rect(x+statusOffset,y,w-statusOffset,34),status,labelStyle);
        y+=37;
        if (response == null)
        { GUI.Label(new Rect(x,y,w,90),"MODELO ELÁSTICO LINEAL\nCada intensidad se analiza en OpenSees. La escala visual cambia solo la geometría mostrada.\nSeleccione una barra para los chequeos disponibles y la fisuración ilustrativa.",labelStyle); return; }
        SeismicMetadata m=response.Metadata;
        GUI.Label(new Rect(x,y,w,22),$"{(playing ? "PLAYING" : "PAUSED")} · t={playTime:0.00}/{m.duration:0.00} s · PGA registro={m.pgaOriginal_m_s2/9.80665f:0.000} g → aplicada={m.pgaApplied_m_s2/9.80665f:0.000} g · {m.intensity:0.00}x · {m.direction} · ζ={m.modal.dampingRatio*100:0.#}%",labelStyle);
        y+=24;
        if (GUI.Button(new Rect(x,y,70,23),"PLAY")) playing=true;
        if (GUI.Button(new Rect(x+76,y,70,23),"PAUSE")) playing=false;
        if (GUI.Button(new Rect(x+152,y,80,23),"RESTART")) { playTime=0; playing=false; }
        float timeline=GUI.HorizontalSlider(new Rect(x+250,y+6,w-250,18),playTime,0,m.duration);
        if (Mathf.Abs(timeline-playTime)>.0001f) { playTime=timeline; playing=false; }
        y+=28;
        GUI.Label(new Rect(x,y,100,22),$"Velocidad {speed:0.00}x",labelStyle);
        speed=GUI.HorizontalSlider(new Rect(x+108,y+5,130,18),speed,.25f,2f);
        GUI.Label(new Rect(x+257,y,145,22),$"Escala visual {visualScale:0}x",labelStyle);
        visualScale=GUI.HorizontalSlider(new Rect(x+405,y+5,130,18),visualScale,1,200);
        showOriginal=GUI.Toggle(new Rect(x+552,y,125,22),showOriginal,"Original tenue");
        y+=27;
        int frame=response.FrameAt(playTime), criticalNode=0; float max=0;
        for(int n=0;n<m.nodeTags.Length;n++) { float value=response.ReadNode(frame,n).magnitude;
            if(value>max) {max=value;criticalNode=m.nodeTags[n];} }
        GUI.Label(new Rect(x,y,w,23),$"MÁX REAL ACTUAL {max*1000:0.###} mm · nodo {criticalNode} | MÁX REGISTRO {m.maximumDisplacement.value_m*1000:0.###} mm · nodo {m.maximumDisplacement.nodeTag} · t={m.maximumDisplacement.time:0.00}s",labelStyle);
        y+=25;
        if (selected >= 0)
        {
            SeismicMember member=m.members[selected];
            GUI.Label(new Rect(x,y,w,20),$"{member.elementTag} · ID {member.id} · {member.type} · {member.sectionId} · muestra real t={response.Time(frame):0.000}s",titleStyle);
            y+=22;
            float nI=-response.ReadEndForce(frame,selected,0),nJ=response.ReadEndForce(frame,selected,6);
            GUI.Label(new Rect(x,y,w,42),$"I: N={nI:0.##} kN · Vy={response.ReadEndForce(frame,selected,1):0.##} kN · Vz={response.ReadEndForce(frame,selected,2):0.##} kN · My={response.ReadEndForce(frame,selected,4):0.##} kN·m · Mz={response.ReadEndForce(frame,selected,5):0.##} kN·m\nJ: N={nJ:0.##} kN · Vy={-response.ReadEndForce(frame,selected,7):0.##} kN · Vz={-response.ReadEndForce(frame,selected,8):0.##} kN · My={-response.ReadEndForce(frame,selected,10):0.##} kN·m · Mz={-response.ReadEndForce(frame,selected,11):0.##} kN·m",labelStyle);
            y+=46;
            DrawDamage(frame,x,y,w);
        }
        else GUI.Label(new Rect(x,y,w,40),"Clic o ID/tag: esfuerzos, chequeos disponibles y fisuración del elemento.\nRespuesta total G+0.5Q+sismo · desplazamientos relativos al terreno · modelo elástico.",labelStyle);
    }

    private SeismicDamageProfile DamageProfile(SeismicMember member)
    {
        var profile=new SeismicDamageProfile { Width=member.width_m,Height=member.height_m,
            Check=SeismicPMCheck.None,Source="Sin capacidad última exportada",
            Limitation="No se adopta As mínima como armadura real. Corte, torsión, fatiga y daño constitutivo no evaluados." };
        PMCurveData curve=UnityData.GetPMCurve(member.sectionId);
        if(curve == null && member.type == "columna" && member.sectionId == "COL70/70")
            curve=UnityData.GetPMCurve("COL70/70_FIBER");
        if(curve == null && member.type == "muro_eq" && member.sectionId.StartsWith("MURO_",StringComparison.Ordinal))
            curve=UnityData.GetPMCurve("W_"+member.sectionId.Substring(5));
        if(curve == null && member.type == "muro_eq" && UnityData.Structure.p1l4.pmCurves != null)
            foreach(PMCurveData candidate in UnityData.Structure.p1l4.pmCurves)
                if(candidate.elementType == "muro" && Mathf.Abs(candidate.b_m-Mathf.Min(member.width_m,member.height_m))<.001f &&
                    Mathf.Abs(candidate.h_m-Mathf.Max(member.width_m,member.height_m))<.001f)
                { if(curve != null) { curve=null; break; } curve=candidate; }
        SectionMaterialData material=UnityData.GetMaterial(curve != null ? curve.sectionId : member.sectionId);
        if(material == null) material=UnityData.GetMaterial(member.sectionId);
        if(material != null) profile.FcMPa=material.fc_MPa;
        bool dimensionsMatch=curve != null && (member.type == "muro_eq" ?
            Mathf.Abs(curve.b_m-Mathf.Min(member.width_m,member.height_m))<.001f &&
                Mathf.Abs(curve.h_m-Mathf.Max(member.width_m,member.height_m))<.001f :
            Mathf.Abs(curve.b_m-member.width_m)<.001f && Mathf.Abs(curve.h_m-member.height_m)<.001f);
        if(!dimensionsMatch || material == null || material.Ast_mm2<=0 || curve.points == null ||
            Mathf.Abs(curve.fc_MPa-material.fc_MPa)>.01f) return profile;
        if(member.type != "muro_eq" && (material.topBars<=0 || material.topBars!=material.bottomBars))
        {
            profile.Source="Faltan curvas P-M por signo para esta armadura asimétrica";
            return profile;
        }
        profile.Curve=Array.ConvertAll(curve.points,p=>new SeismicCapacityPoint(p.P_kN,Math.Abs(p.M_kN_m)));
        profile.Check=member.type == "muro_eq" ? (member.height_m>=member.width_m ? SeismicPMCheck.My : SeismicPMCheck.Mz) :
            // Equality of axes requires rotational, not just mirror, symmetry.
            // 5 upper + 5 lower + 4 interior/side is NOT invariant under 90 degrees.
            Mathf.Abs(member.width_m-member.height_m)<.001f && material.topBars>=2 &&
                material.topBars==material.bottomBars && material.sideBarsEach==material.topBars-2
                ? SeismicPMCheck.IndependentAxes : SeismicPMCheck.My;
        profile.Source="P-M nominal: "+curve.sectionId+" ("+curve.points.Length+" puntos)";
        profile.Limitation=profile.Check == SeismicPMCheck.IndependentAxes ?
            "Chequeos P–My y P–Mz separados; interacción biaxial, corte y daño constitutivo no evaluados." :
            "Solo P–"+(profile.Check==SeismicPMCheck.My ? "My" : "Mz")+"; no evalúa el otro eje, corte ni daño constitutivo.";
        if((curve.interpretation ?? "").IndexOf("supuesta",StringComparison.OrdinalIgnoreCase)>=0)
            profile.Limitation+=" Armadura de muro SUPUESTA en la exportación.";
        return profile;
    }

    private void EnsureDamageHistory()
    {
        if(response == null || selected<0 || selected==damageMember) return;
        crackVisual.Clear();damageHistory=null;damageError=null;damageMember=selected;
        var member=response.Metadata.members[selected];
        double length=Vector3.Distance(response.OriginalNode(response.NodeIndex[member.nodeI]),response.OriginalNode(response.NodeIndex[member.nodeJ]));
        try
        {
            int index=selected;
            damageHistory=SeismicDamageEvaluator.Build(response.Metadata.frameCount,frame=> {
                float[] forces=new float[12];
                for(int k=0;k<12;k++) forces[k]=response.ReadEndForce(frame,index,k);
                return forces;
            },length,DamageProfile(member));
        }
        catch(ArgumentException e) { damageError=e.Message; }
    }

    private string EventTime(int frame) => frame<0 ? "no registrado" :
        response.Time(frame).ToString("0.00",CultureInfo.InvariantCulture)+" s"+(frame==0 ? " (gravedad)" : "");
    private static string Ratio(double ratio) => double.IsNaN(ratio) ? "N/D" : double.IsInfinity(ratio) ? "∞" : ratio.ToString("0.000",CultureInfo.InvariantCulture);
    private void JumpToEvent(int frame)
    { if(frame>=0) { playing=false;playTime=response.Time(frame);crackVisual.Replay(); } }
    private void FocusMemberNow()
    {
        Camera camera=Camera.main;
        if(camera == null) return;
        foreach(MeshBar bar in bars) if(bar.member==selected)
        {
            // Fit the member in the unobstructed viewport, above the results card.
            StructureViewer viewer=GetComponent<StructureViewer>();
            float top=viewer!=null && viewer.IsTopBarVisible() ? viewer.GetTopBarRect().yMax+12 : 12;
            float bottom=PanelRect.y-12,left=PanelRect.x;
            float verticalFraction=Mathf.Max(.15f,(bottom-top)/Screen.height);
            Vector3 size=bar.transform.localScale;
            float projectedHeight=Mathf.Abs(Vector3.Dot(bar.transform.right,camera.transform.up))*size.x+
                Mathf.Abs(Vector3.Dot(bar.transform.up,camera.transform.up))*size.y+
                Mathf.Abs(Vector3.Dot(bar.transform.forward,camera.transform.up))*size.z;
            float projectedWidth=Mathf.Abs(Vector3.Dot(bar.transform.right,camera.transform.right))*size.x+
                Mathf.Abs(Vector3.Dot(bar.transform.up,camera.transform.right))*size.y+
                Mathf.Abs(Vector3.Dot(bar.transform.forward,camera.transform.right))*size.z;
            float tangent=Mathf.Tan(camera.fieldOfView*Mathf.Deg2Rad*.5f);
            float distance=Mathf.Max(4f,projectedHeight*1.16f/(2*tangent*verticalFraction));
            distance=Mathf.Max(distance,projectedWidth*1.16f/(2*tangent*camera.aspect*Mathf.Max(.2f,(Screen.width-left-16)/Screen.width)));
            float viewHeight=2*distance*tangent,viewWidth=viewHeight*camera.aspect;
            float dx=(((left+Screen.width)*.5f)/Screen.width-.5f)*viewWidth;
            float dy=(.5f-((top+bottom)*.5f)/Screen.height)*viewHeight;
            camera.GetComponent<OrbitCamera>()?.FocusOn(bar.transform.position-camera.transform.right*dx-camera.transform.up*dy,distance);
            break;
        }
    }
    private void DrawDamage(int frame,float x,float y,float width)
    {
        if(damageHistory == null || damageMember!=selected)
        {GUI.Label(new Rect(x,y,width,54),"NO EVALUADO — "+(damageError ?? "Preparando historial del elemento…"),labelStyle);return;}
        var h=damageHistory;var current=h.Samples[frame];var peak=h.Samples[h.PeakDCRFrame[frame]];
        bool cracked=h.FirstCrack>=0 && frame>=h.FirstCrack;
        string state=!h.Profile.HasCapacity ? (cracked ? "FISURACIÓN ESTIMADA · CAPACIDAD ÚLTIMA N/D" : "CAPACIDAD ÚLTIMA NO DISPONIBLE") :
            current.State==SeismicDemandState.CAPACITY_EXCEEDED ? "EXCEDE CAPACIDAD P-M NOMINAL" :
            current.State==SeismicDemandState.NEAR_CAPACITY ? "CERCA DE CAPACIDAD P-M" :
            current.State==SeismicDemandState.HIGH_DEMAND ? "DEMANDA P-M ALTA" : "NO EXCEDE CHEQUEOS P-M";
        Color old=GUI.color;
        GUI.color=current.State==SeismicDemandState.CAPACITY_EXCEEDED ? new Color(1,.35f,.25f) :
            cracked || (current.State==SeismicDemandState.HIGH_DEMAND || current.State==SeismicDemandState.NEAR_CAPACITY) && h.Profile.HasCapacity ? new Color(1,.78f,.28f) : new Color(.5f,.85f,1f);
        string demandCapacity=h.Profile.HasCapacity ? $" · D/C={current.Demand:0.#}/{current.Capacity:0.#} {(current.AxialLimit ? "kN" : "kN·m")}" : "";
        GUI.Label(new Rect(x,y,width,22),state+" · DCR "+Ratio(current.DCR)+demandCapacity+" · máx hasta ahora "+Ratio(peak.DCR),damageTitleStyle);
        GUI.color=old;y+=22;
        string cracking=h.Profile.HasCracking ?
            $"σt estimada={current.TensileMPa:0.00} MPa / fr={h.Profile.RuptureMPa:0.00} MPa · primera fisuración: {EventTime(h.FirstCrack)}" : "Sin propiedades para estimar fisuración.";
        GUI.Label(new Rect(x,y,width,20),cracking+" · primera excedencia P-M: "+EventTime(h.FirstExceeded),labelStyle);y+=22;
        GUI.Label(new Rect(x,y,width,58),h.Profile.Source+" · "+h.Profile.Limitation+"\nGRIETAS ILUSTRATIVAS según máximos hasta el tiempo actual; no predicen fractura, ancho real ni pérdida de rigidez.",labelStyle);y+=61;
        showCracks=GUI.Toggle(new Rect(x,y,143,24),showCracks,"Ver fisuración 3D");
        bool enabled=GUI.enabled;
        GUI.enabled=enabled && h.FirstCrack>=0;
        if(GUI.Button(new Rect(x+151,y,165,24),"ANIMAR FISURACIÓN"))
        {showCracks=true;isolateSelected=true;if(frame<h.FirstCrack) JumpToEvent(h.FirstCrack);crackVisual.Replay();focusRequested=true;}
        GUI.enabled=enabled && h.FirstCrack>=0;
        if(GUI.Button(new Rect(x+322,y,150,24),"IR A PRIMERA FISURA")) JumpToEvent(h.FirstCrack);
        GUI.enabled=enabled && h.FirstExceeded>=0;
        if(GUI.Button(new Rect(x+478,y,150,24),"IR A EXCEDENCIA")) JumpToEvent(h.FirstExceeded);
        GUI.enabled=enabled;
        if(GUI.Button(new Rect(x+634,y,90,24),"ENFOCAR")) focusRequested=true;
        isolateSelected=GUI.Toggle(new Rect(x+730,y,150,24),isolateSelected,"Solo seleccionado");
    }
}
